#!/bin/bash 

# Check if sufficient arguments are provided
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <PID> <Duration> <Output Dir>"
    exit 1
fi

# Assign command line arguments to variables
PID=$1
DURATION=$2
DIR=$3

sudo perf stat -e instructions,cycles,icache.misses -p "$PID" sleep "$DURATION" 2>&1 | tee "$DIR/$(ps -p "$PID" -o comm=)_${PID}_CPU.out"

sudo perf stat --topdown -p $PID sleep $DURATION 2>&1 | tee "$DIR/$(ps -p $PID -o comm=)_${PID}_topdown.out"

