#!/bin/bash

#sudo cpupower frequency-set --min 2.45G
#sudo cpupower frequency-set --max 2.45G

pwd

cd ../mediaMicroservices

pwd

# run docker containers
docker-compose down

sleep 5

cd ..

cd socialNetwork

# run docker containers
docker-compose down
docker volume rm $(docker volume ls -q)
docker-compose up -d

sleep 10

# fill the databases
python3 scripts/init_social_graph.py --graph=socfb-Reed98
