#!/bin/bash

pwd

cd ../DeathStarBench/mediaMicroservices

pwd

# run docker containers
sudo docker-compose down

sleep 5

cd ..

cd socialNetwork

# run docker containers
sudo docker-compose down
sudo docker volume rm $(docker volume ls -q)
