#!/bin/bash 
 
SIM_TIME=2200s # needs to be at least 30 seconds PER PROCESS according to Shanqing!
APPLICATION_DIR="../mediaMicroservices"

sleep 5
printf "Generating workload... \n"

#Generate workload 
../wrk2/wrk -D exp -t 2 -c 100 -d $SIM_TIME -L -s $APPLICATION_DIR/wrk2/scripts/media-microservices/compose-review.lua http://10.89.3.7:8080/wrk2-api/review/compose -R 500 #IP Address of iccluster 113

printf "End of workload generation. \n"
